[package]
name = "firecore-util"
version = "0.3.0-beta.2"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tinystr = { version = "0.4", features = ["serde"] }